# Generated by Django 3.2.23 on 2024-01-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_profiles',
            new_name='user_profile',
        ),
    ]
